翻译了线缆和控制器
LittleCircleOO/Applied-Energistics-2_Guide_zhcn pull request #1
Opened 2024-03-19 11:38 UTC by OLDRedstone

2024-03-23 04:55 UTC, LittleCircleOO requested changes
建议调整部分措辞

2024-03-23 04:55 UTC, LittleCircleOO commented on guidebook/items-blocks-machines/cables.md
> +虽然的具有 ME 功能的彼此相连的机械也能构建一个 ME 网络，但是线缆是将 ME 网络扩展到更大的区域的主要方式。
```suggestion
虽然毗邻的支持 ME 的机器也能构建一个 ME 网络，但是线缆是将 ME 网络扩展到更大的区域的主要方式。
```
尝试修改措辞以避免歧义

2024-03-23 04:55 UTC, LittleCircleOO commented on guidebook/items-blocks-machines/cables.md
> +线缆本身的颜色也会影响附着到线缆上的端口的颜色, 所以你不必把所有终端染成紫色。
```suggestion
使用不同颜色的线缆可确保相邻线缆不会相互连接，从而更高效地分配[频道](../ae2-mechanics/channels.md)。
线缆本身的颜色也会影响附着到线缆上的终端的颜色, 所以你不必把所有终端染成紫色。
```
尽量使用标准译名，参考 AE2 译名对照表

2024-03-23 04:55 UTC, LittleCircleOO commented on guidebook/items-blocks-machines/cables.md
> +**如果你不熟悉 AE2 及其频道，请尽可能使用智能线缆和致密智能线缆。它们将显示频道在你的网络里是如何流通的，这样能更便于理解频道的工作方式。** 
```suggestion
**如果你不熟悉 AE2 及其频道，请尽可能使用智能线缆和致密线缆。它们将显示频道在你的网络里是如何路由的，这样能更便于理解频道的工作方式。** 
```

2024-03-23 04:55 UTC, LittleCircleOO commented on guidebook/items-blocks-machines/cables.md
> +也可以用与 Forge 兼容的任意画刷对线缆染色。
重新核实是否丢失了部分信息
`To craft colored cables...`

2024-03-23 04:55 UTC, LittleCircleOO commented on guidebook/items-blocks-machines/cables.md
> +所以在使用总线或者面板之前，你需要从致密线缆降级至更小的线缆（例如<ItemLink id="fluix_glass_cable" />和<ItemLink id="fluix_smart_cable" />。
```suggestion
更大容量的线缆。相较于其他只能承载 8 个频道的普通线缆，致密线缆可以承载 32 个频道。致密线缆不支持总线，
所以在使用总线或者面板之前，你需要从致密线缆降级至更小的线缆（例如<ItemLink id="fluix_glass_cable" />或<ItemLink id="fluix_smart_cable" />。  
```
同样是标准译名与表述问题。

2024-03-23 04:55 UTC, LittleCircleOO commented on guidebook/items-blocks-machines/cables.md
> +可以使用和<ItemLink id="fluix_glass_cable" />相同的方式为包层线缆染色。使用 4 个<ItemLink id="fluix_covered_cable" />以及红石和荧石制作<ItemLink id="fluix_covered_dense_cable" />。 
> 使用 4 个`福鲁伊克斯色ME包层线缆`以及红石和荧石制作`福鲁伊克斯色ME致密包层线缆`。

此处存在事实性错误，由于原文如此可暂不作修改，待上游更正后进行修改。

2024-03-23 04:55 UTC, LittleCircleOO commented on guidebook/items-blocks-machines/cables.md
> +致密线缆轻量重写了频道的“最短路径”行为。频道会先使用到达致密线缆的最短路径，然后使用通过致密线缆到达 ME 控制器的最短路径。 
```suggestion
致密线缆略微覆盖了频道的“最短路径”行为，频道将以最短路径到达致密线缆，然后以最短路径通过致密线缆到达控制器。
```
中文表达调整。

2024-03-23 04:55 UTC, LittleCircleOO commented on guidebook/items-blocks-machines/cables.md
> +对于普通的智能线缆，前四个频道显示为与线缆颜色相同的颜色的线条，后四个频道显示为白色线条。
```suggestion
对于普通的智能线缆，前四个频道显示为与线缆颜色一致的线条，后四个频道显示为白色线条。
```
冗余措辞调整。

2024-03-23 04:55 UTC, LittleCircleOO commented on guidebook/items-blocks-machines/controller.md
> +如果没有控制器，网络就是“临时”的，且最多只能有总共 8 台[设备](../ae2-mechanics/devices.md)使用通道。 
```suggestion
控制器相当于 [ME 网络](../ae2-mechanics/me-network-connections.md) 的集线器。
如果没有控制器，网络就是“临时”的，且最多只能有总共 8 台 [设备](../ae2-mechanics/devices.md) 使用频道。
```
标准化译名

2024-03-23 04:55 UTC, LittleCircleOO commented on guidebook/items-blocks-machines/controller.md
> +同一个[ ME 网络](../ae2-mechanics/me-network-connections.md)中不能有多个控制器。 
```suggestion
同一个 [ME 网络](../ae2-mechanics/me-network-connections.md) 中不能有多个控制器。  
```

2024-03-23 04:55 UTC, LittleCircleOO commented on guidebook/items-blocks-machines/controller.md
> +控制器的每个面提供 32 个[通道](../ae2-mechanics/channels.md)。 
```suggestion
控制器的每个面提供 32 个 [频道](../ae2-mechanics/channels.md)。  
```
标准化译名

2024-03-23 04:55 UTC, LittleCircleOO commented on guidebook/items-blocks-machines/controller.md
> +## 合成 
```suggestion

## 配方
```

2024-03-23 04:55 UTC, LittleCircleOO commented on guidebook/items-blocks-machines/controller.md
```suggestion
```
换行错位

2024-03-26 03:16 UTC, OLDRedstone commented on guidebook/items-blocks-machines/cables.md
> +**如果你不熟悉 AE2 及其频道，请尽可能使用智能线缆和致密智能线缆。它们将显示频道在你的网络里是如何流通的，这样能更便于理解频道的工作方式。** 
致密线缆也包括包层线缆吧（

2024-03-26 04:06 UTC, OLDRedstone reviewed
翻译修改

2024-03-26 05:11 UTC, LittleCircleOO commented on guidebook/items-blocks-machines/cables.md
> +**如果你不熟悉 AE2 及其频道，请尽可能使用智能线缆和致密智能线缆。它们将显示频道在你的网络里是如何流通的，这样能更便于理解频道的工作方式。** 
> 致密线缆也包括致密包层线缆吧（

译名如此

2024-03-26 05:12 UTC, LittleCircleOO approved these changes

2024-03-26 05:15 UTC, merged